#!/bin/bash
#This script file merges files from the /dist folder into the /site-template folder, to generate
#a complete ConnextCMS site template.

echo "building connextcms-vue-app directory..."

rm -rf connextcms-vue-app
cp -r site-template-connextcms connextcms-vue-app
cd dist
cp index.html ../connextcms-vue-app/keystone/views/app-dashboard.hbs
cd static
mkdir ../../connextcms-vue-app/public
cp -r css ../../connextcms-vue-app/public/styles
cp -r img ../../connextcms-vue-app/public/images
cp -r js ../../connextcms-vue-app/public/js

echo "...Done!"